# Generated by Django 5.0.13 on 2025-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_orderdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
