# Generated by Django 5.0.13 on 2025-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_rename_qty_orderdata_quantity_orderdata_api_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='actual_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
