# Generated by Django 5.0.13 on 2025-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_masterinventory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='masterinven_item_fe0ce4_idx',
            old_name='Portal_mast_item_2d1a7d_idx',
        ),
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='masterinven_status_3f1bb7_idx',
            old_name='Portal_mast_status_c63450_idx',
        ),
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='masterinven_import__1d73c2_idx',
            old_name='Portal_mast_import__27b1dc_idx',
        ),
        migrations.AlterModelTable(
            name='masterinventory',
            table='masterinventory_data',
        ),
    ]
