# Generated by Django 5.0.13 on 2025-03-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_orderdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('process_excel', 'Process Excel Files'), ('create_api_orders', 'Create API Orders'), ('check_pick_status', 'Check Pick Status'), ('process_inventory_files', 'Process Inventory Files'), ('create_inventory_api', 'Create Inventory API')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency', models.IntegerField(default=60, help_text='Frequency in seconds')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Configuration',
                'verbose_name_plural': 'Task Configurations',
            },
        ),
    ]
