# Generated by Django 5.0.13 on 2025-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_alter_taskconfig_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfig',
            name='task_name',
            field=models.CharField(choices=[('Portal.tasks.import_order.process_excel_files', 'Process Excel Files'), ('Portal.tasks.api_order_creation.create_api_orders', 'Create API Orders'), ('Portal.tasks.check_pick_status', 'Check Pick Status'), ('Portal.tasks.import_inventory.process_inventory_files', 'Process Inventory Files'), ('Portal.tasks.api_inventory.api_inventory_creation', 'Create Inventory API')], max_length=255, unique=True),
        ),
    ]
