# Generated by Django 5.0.13 on 2025-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0012_warehouselocation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='warehouselocation',
            table='Portal_warehouse_location',
        ),
    ]
