# Generated by Django 5.0.13 on 2025-03-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0022_rename_masterinven_item_fe0ce4_idx_portal_mast_item_e4e8ce_idx_and_more'),
        ('Portal', '0023_create_staging_orders_table'),
    ]

    operations = [
    ]
