# Generated by Django 5.0.13 on 2025-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0024_merge_20250329_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagingorder',
            options={'ordering': ['order_number', 'order_line']},
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='task_name',
            field=models.CharField(choices=[('Portal.tasks.import_order.process_excel_files', 'Excel - Order File Import'), ('Portal.tasks.api_order_creation.create_api_orders', 'API - Create Orders'), ('Portal.tasks.check_pick_status', 'API - Check Order Status'), ('Portal.tasks.import_inventory.process_inventory_files', 'Excel - Inventory File Import'), ('Portal.tasks.api_inventory.api_inventory_creation', 'API - Create Inventory API'), ('Portal.tasks.export_order.export_completed_orders', 'Excel - Order Export')], max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='stagingorder',
            table='Portal_staging_orders',
        ),
    ]
