# Generated by Django 5.0.13 on 2025-03-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_update_task_names'),
        ('Portal', '0024_transactionlog'),
    ]

    operations = [
    ]
