# Generated by Django 5.0.13 on 2025-03-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0024_add_db_import_task'),
        ('Portal', '0025_alter_stagingorder_options_and_more'),
    ]

    operations = [
    ]
