# Generated by Django 5.0.13 on 2025-03-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_fix_task_names'),
        ('Portal', '0025_merge_0002_update_task_names_0024_transactionlog'),
    ]

    operations = [
    ]
