# Generated by Django 5.0.13 on 2025-03-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_add_vlm_demo_task'),
        ('Portal', '0026_merge_20250331_2147'),
    ]

    operations = [
    ]
