# Generated by Django 5.0.13 on 2025-03-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0025_add_db_import_task_choice'),
        ('Portal', '0026_merge_20250329_1931'),
    ]

    operations = [
    ] 