version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./Files:/app/Files
    env_file:
      - .env
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A CompactNodeInt worker -l INFO
    volumes:
      - .:/app
      - ./Files:/app/Files
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A CompactNodeInt beat -l INFO
    volumes:
      - .:/app
      - ./Files:/app/Files
    env_file:
      - .env
    depends_on:
      - redis
      - celery

volumes:
  redis_data: 