# Generated by Django 5.0.13 on 2025-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_remove_orderdata_order_id_alter_orderdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='api_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='sent_status',
            field=models.IntegerField(default=0),
        ),
    ]
