# Generated by Django 5.0.13 on 2025-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_orderdata_actual_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=10)),
                ('cus1', models.CharField(blank=True, max_length=255, null=True)),
                ('cus2', models.CharField(blank=True, max_length=255, null=True)),
                ('cus3', models.CharField(blank=True, max_length=255, null=True)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Master Inventory',
                'verbose_name_plural': 'Master Inventory',
                'indexes': [models.Index(fields=['item'], name='Portal_mast_item_2d1a7d_idx'), models.Index(fields=['status'], name='Portal_mast_status_c63450_idx'), models.Index(fields=['import_timestamp'], name='Portal_mast_import__27b1dc_idx')],
            },
        ),
    ]
