# Generated by Django 5.0.13 on 2025-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_taskconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfig',
            name='task_name',
            field=models.CharField(choices=[('process_excel_files', 'Process Excel Files'), ('create_api_orders', 'Create API Orders'), ('check_pick_status', 'Check Pick Status'), ('process_inventory_files', 'Process Inventory Files'), ('create_inventory_api', 'Create Inventory API')], max_length=50, unique=True),
        ),
    ]
