# Generated by Django 5.0.13 on 2025-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0011_alter_taskconfig_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wms_location', models.CharField(max_length=100)),
                ('cn_bin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Warehouse Location',
                'verbose_name_plural': 'Warehouse Locations',
                'db_table': 'warehouse_location',
            },
        ),
    ]
