# Generated by Django 5.0.13 on 2025-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0013_alter_warehouselocation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='bin_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='wms_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
