# Generated by Django 5.0.13 on 2025-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0016_alter_orderdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
