# Generated by Django 5.0.13 on 2025-03-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0021_alter_taskconfig_task_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='Portal_mast_item_e4e8ce_idx',
            old_name='masterinven_item_fe0ce4_idx',
        ),
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='Portal_mast_status_8d4bf2_idx',
            old_name='masterinven_status_3f1bb7_idx',
        ),
        migrations.RenameIndex(
            model_name='masterinventory',
            new_name='Portal_mast_import__481645_idx',
            old_name='masterinven_import__1d73c2_idx',
        ),
        migrations.AlterModelTable(
            name='masterinventory',
            table='Portal_masterinventory_data',
        ),
        migrations.AlterModelTable(
            name='orderdata',
            table='Portal_order_data',
        ),
    ]
