# Generated by Django 5.0.13 on 2025-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0022_rename_masterinven_item_fe0ce4_idx_portal_mast_item_e4e8ce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfig',
            name='task_name',
            field=models.CharField(choices=[('Portal.tasks.import_order.process_excel_files', 'Excel - Order File Import'), ('Portal.tasks.api_order_creation.create_api_orders', 'API - Create Orders'), ('Portal.tasks.check_pick_status', 'API - Check Order Status'), ('Portal.tasks.import_inventory.process_inventory_files', 'Excel - Inventory File Import'), ('Portal.tasks.api_inventory.api_inventory_creation', 'API - Create Inventory API'), ('Portal.tasks.export_order.export_completed_orders', 'Excel - Order Export'), ('Portal.tasks.vlm_demo.process_demo_orders', 'VLM - Demo Mode')], max_length=255, unique=True),
        ),
    ]
