# Generated by Django 5.0.13 on 2025-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0023_alter_taskconfig_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=36)),
                ('order_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
